server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: todo-list-backend
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db_reactive_todo_list
      username: magadiflo
      password: magadiflo
      authentication-database: admin

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG